### ISSUE TITLE
Build a (minified) version for CDN delivery

### ISSUE THREAD

**Issue by Fubinator** [turingpointde/cvss.js#31]
Currently the user has to install the library with a package manager. I think it would be a good idea to build a (minified) version of the lib each time the `main` branch gets updated. This way the user can just include a script tag with a CDN's url (e.g. https://unpkg.com/@turingpointde/cvss.js@1.2.0/production.min.js) and use the library.

I do not really know if GitHub Actions can modify commits or add this to a merge commit. But what we would need ideally is:

1. A config/tool to build a (minified) version of the library
2. A Github action that builds the library automatically and updates the repo if changes are merged into main

**Comment by amstr4d** [comment]
Hello ! I really would like to work on this one. But I think this issue should be split in two : one for the minification tool and one for the CD part with Github actions.

**Comment by mrewers** [comment]
Hey @amstr4d. Sorry, I didn't mean to snag this out from under you. I pushed up my PR (#34) for this before seeing your comment. My solution to the second part of this issue is probably a bit unsatisfactory (see the description in the PR) and I didn't use GitHub actions as suggested. Maybe you want to pick up where I left off in my PR?

**Comment by amstr4d** [comment]
Hi @mrewers ! No problems, your solution seems pretty nice. I can still work on the Github Actions part, but maybe on a different issue, as @Fubinator mentionned in your PR.

**Comment by Fubinator** [comment]
@mrewers @amstr4d I opened #35 for the GitHub action part.
